version: '3.9'

services:
  django-web:
    env_file:
      - ./.env
    build: ./web
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", 'healthcheck.sh' ]
      start_period: 1m
      start_interval: 10s
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    volumes:
          - django-logs:/usr/src/app/logs
          - django-backups:/usr/src/app/backups

  flask-service:
    env_file:
      - ./.env
    build: ./service
    ports:
      - "8016:8016"
    healthcheck:
      test: ["CMD","python", "healthcheck.py", "|| exit 1" ]
      start_period: 1m
      start_interval: 10s
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
      redis-cache:
        condition: service_healthy

  postgres-db:
    # https://hub.docker.com/_/postgres
    image: postgres:16
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      start_period: 1m
      start_interval: 10s
      interval: 30s
      timeout: 5s
      retries: 3
    env_file:
      - ./.env
    restart: always
    volumes:
          - db-data:/var/lib/postgresql/data
          
  redis-cache:
    # https://hub.docker.com/r/redis/redis-stack-server
    image: redis/redis-stack-server
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      start_period: 1m
      start_interval: 10s
      interval: 15s
      timeout: 5s
      retries: 3
    env_file:
      - ./.env
    restart: always

volumes:
  db-data:
  django-logs:
  django-backups: