version: '3.9'

services:
  postgres-db:
    # https://hub.docker.com/_/postgres
    image: postgres:16
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      start_period: 1m
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./.env
    restart: always
    volumes:
          - db-data:/var/lib/postgresql/data
          
  redis-cache:
    # https://hub.docker.com/r/redis/redis-stack-server
    image: redis/redis-stack-server
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      start_period: 1m
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./.env
    restart: always

volumes:
  db-data: